#!/bin/bash
input=${1%/}	#removes trailing slash if present
size=$2		#Small Big

#set these appropriately
unifiedDir='/Users/garyunderwood/corpora/unifiedVersion3/split'

if [[ ! -d "$DEID_DIR" ]]
then
	echo "Must set DEID_DIR first, should be absolute path to deid/java-app"
	exit 1
fi

if [[ $size == "big" ]]; then size=Big; fi
if [[ $size == "small" ]]; then size=Small; fi
if [[ $size != "Big" && $size != "Small" ]]; then 
	echo "Size should be Small or Big"
	exit 3
fi
if [[ -z $3 || $3 == "clean" || $2 == "filtered" ]] 	#default to clean
then
	ext='.filtered-system-output'
elif [[ $3 == "raw" || $2 == "complete" ]] ; then
	ext='.complete-system-output'
elif [[ $3 == "acv" ]] ; then
	acvDir="acv-$input"
	acv="--reference-out $acvDir/reference/ --test-out $acvDir/system/ --corpus-out $acvDir/corpus.json"
	mkdir -p $acvDir
	mkdir -p $acvDir/reference
	mkdir -p $acvDir/system
else 
	ext=$3
fi

if [[ -z $4 ]] ; then	#default to clean
	acv=""
elif [[ $4 == "acv" ]] ; then
	acvDir="acv-$input"
	acv="--reference-out $acvDir/reference/ --test-out $acvDir/system/ --corpus-out $acvDir/corpus.json"
	mkdir -p $acvDir
	mkdir -p $acvDir/reference
	mkdir -p $acvDir/system
fi
ext='.clean-system-output'
echo "Output files $input, size $size, with extention $ext"
echo "acv=$acv"
file=results-$input-ByFile.txt

python3 ~/ETUDE/etude.py --reference-input $unifiedDir/testXml$size --reference-config $DEID_DIR/etude-configs/UnifiedGold-EndToEnd-Split.conf \
	--test-input $input --test-config $DEID_DIR/etude-configs/UnifiedDeid-EndToEnd-Split.conf  --fuzzy-match-flags exact fully-contained partial \
	--file-suffix ".xml" "$ext.xml" --score-key Parent -m TP FP FN Precision Recall F1 --by-file-and-type $acv \
	>$file-1 &
	#| $DEID_DIR/scripts/etudePrettyPipeByFileType.pl 	

python3 ~/ETUDE/etude.py --reference-input $unifiedDir/testXml$size --reference-config $DEID_DIR/etude-configs/UnifiedGold-EndToEnd-Split.conf \
	--test-input $input --test-config $DEID_DIR/etude-configs/UnifiedDeid-EndToEnd-Split.conf  --fuzzy-match-flags exact fully-contained partial \
	--file-suffix ".xml" "$ext.xml" --score-key Top -m TP FP FN Precision Recall F1 --by-file-and-type \
	 >$file-2 &
	#| $DEID_DIR/scripts/etudePrettyPipeByFileType.pl

python3 ~/ETUDE/etude.py --reference-input $unifiedDir/testXml$size --reference-config $DEID_DIR/etude-configs/UnifiedGold-EndToEnd-Split.conf \
	--test-input $input --test-config $DEID_DIR/etude-configs/UnifiedDeid-EndToEnd-Split.conf  --fuzzy-match-flags exact fully-contained partial \
	--file-suffix ".xml" "$ext.xml" --score-key Root -m TP FP FN Precision Recall F1 --by-file-and-type \
	 >$file-2 &
	#| $DEID_DIR/scripts/etudePrettyPipeByFileType.pl

wait

echo "$input folder with size $size using $ext" >$file
echo "Sub PII category"
cat $file-1 >> $file
echo "" >>$file
echo "Parent PII category" >>$file
cat $file-2 >>$file
echo "" >>$file
echo "Root PII" >>$file
cat $file-3 >>$file
rm $file-3 $file-2 $file-1

cat $file
