#! /bin/bash
if [ -f resultsForDevelop.txt ]; then
	mv resultsForDevelop.txt extraFiles/resultsForMaster.txt
	cd extraFiles
	if [ -d developOutput ]; then
		rm -r masterOutput
		mv developOutput masterOutput
	else
		echo "no developOutput folder to rename"
	fi
else 
	echo "No resultsForDevelop.txt file"
fi
